version: '3'

services:
  telegraf:
    image: telegraf:1.13
    ports:
    - 8094:8094
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  monitor:
    build:
      context: ../..
    command: gather-for-telegraf
    environment:
      GATHER_INTERVAL: 10s
      GATHER_TELEGRAF_ADDRESS: telegraf:8094
      GATHER_SERVERS: 51.154.166.140